# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI/CD Pipeline with FTP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust based on your Node.js version

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build the frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Deploy to FTP Server
      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp # Can be changed to `sftp` if using secure FTP
          local-dir: ./frontend/build # Adjust to the directory of your frontend build output
          server-dir: /path/to/frontend/on/server # Replace with your desired path on the server

