name: Node.js CI/CD Pipeline with FTP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build the frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Deploy frontend to FTP server
      - name: Deploy Frontend to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./frontend/build/ # Make sure the path ends with a slash
          server-dir: /public_html/university.navicodes.com/frontend


      # Deploy backend to FTP server (optional, adapt as needed)
      - name: Deploy Backend to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./backend/ # Ensure it points to your backend folder
          server-dir: /public_html/university.navicodes.com/backend

